INSTR_BITS = 32
INSTR_BYTE = INSTR_BITS // 8
DATA_BITS = 32
ADDR_BITS = 16

IO_DATA_BUS_SIZE = 32
IO_ADDR_BUS_SIZE = 16

MC_INSTR_SZ = 64
MC_ADDR_SZ = 11

REG_SZ = 32
REG_PS_SZ = 32

REGFILE_COUNT = 1 << 3

STACK_D_DEPTH = 32
STACK_R_DEPTH = 32

IO_PRINTER_ADDR_BASE = 0x10
IO_PRINTER_ADDR_COUNT = 3
IO_KEYBOARD_ADDR_BASE = 0x20
IO_KEYBOARD_ADDR_COUNT = 0x20
