[tool.poetry]
name = "machine"
version = "1.1.10"
description = ""
authors = ["BardinPetr <bardin.petr@gmail.com>"]
license = "GPLv3"
packages = [
    { include = "machine", from = "src" },
    { include = "mcasm", from = "src" },
    { include = "isa", from = "src" },
    { include = "compiler", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.11"
myhdl = "^0.11.45"
pyvcd = "^0.4.0"
lark = "^1.1.9"
lplib = { git = "https://github.com/BardinPetr/lexer-parser.git" }

[tool.poetry.group.test.dependencies]
pytest = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
