[tool.poetry]
name = "mcasm"
version = "0.2.1"
description = ""
authors = ["BardinPetr <bardin.petr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
lark = "^1.1.9"
machine = {path = "../machine"}
setuptools = "^69.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
