INSTR_BITS = 32
DATA_BITS = 32
ADDR_BITS = 32

MC_INSTR_SZ = 32
MC_INSTR_B = MC_INSTR_SZ / 8
MC_ADDR_SZ = 32

ALU_CTRL_BUS_SZ = 8
ALU_CTRL_FLAG_BUS_SZ = 4
ALU_CTRL_PORT_BUS_SZ = 4

CONTROL_BUS_SZ = 64

REG_SZ = 32
REG_PS_SZ = 32

REGFILE_CTRL_SZ = 3
REGFILE_COUNT = 1 << REGFILE_CTRL_SZ