name: Python application

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2

      - name: Poetry local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v3
        name: Cache for poetry venv
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest -v --doctest-modules --junitxml=test-results.xml

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: test-results.xml

  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Python Tests
          path: '*.xml'
          reporter: java-junit